/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;

import UDrawingF2.*;
import Estructuras.*;
import Recursos.*;
import Arboles.*;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import java.io.File;
import java.util.Scanner;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        super("Menu");
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Imagenlbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        comboCapa = new javax.swing.JComboBox<>();
        btnVerCapa = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        comboImagen = new javax.swing.JComboBox<>();
        btnElimiarImg = new javax.swing.JButton();
        btnVerImgAc = new javax.swing.JButton();
        verArboldeCapas = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnModificarDatos = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCarga = new javax.swing.JMenu();
        btnCapas = new javax.swing.JMenuItem();
        btnImagenes = new javax.swing.JMenuItem();
        btnAlbumes = new javax.swing.JMenuItem();
        menuReportes = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        menuVer = new javax.swing.JMenu();
        btnVerArbolCapas = new javax.swing.JMenuItem();
        btnVerArbolImagenes = new javax.swing.JMenuItem();
        btnVerListAlbumes = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Imagenlbl.setBackground(new java.awt.Color(0, 0, 0));
        Imagenlbl.setText("No hay imagen");

        jLabel1.setText("Capa:");

        comboCapa.setName(""); // NOI18N
        comboCapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCapaActionPerformed(evt);
            }
        });

        btnVerCapa.setText("Ver");
        btnVerCapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerCapaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Imagen");

        comboImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboImagenActionPerformed(evt);
            }
        });

        btnElimiarImg.setText("Eliminar");
        btnElimiarImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElimiarImgActionPerformed(evt);
            }
        });

        btnVerImgAc.setText("Ver");
        btnVerImgAc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerImgAcActionPerformed(evt);
            }
        });

        verArboldeCapas.setText("Ver Arbol de Capas");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Capas");

        btnModificarDatos.setText("Modificar Datos");
        btnModificarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarDatosActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setText("MENU UDRAWING");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(comboCapa, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addGap(12, 12, 12)))
                                    .addComponent(comboImagen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnElimiarImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnVerCapa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(btnModificarDatos)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(btnVerImgAc, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(verArboldeCapas)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(Imagenlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(271, 271, 271)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(comboCapa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnVerCapa))
                        .addGap(62, 62, 62)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnElimiarImg))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnVerImgAc)
                            .addComponent(verArboldeCapas)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(35, 35, 35)
                        .addComponent(Imagenlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificarDatos)
                    .addComponent(btnSalir))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        menuCarga.setText("Carga Masiva");

        btnCapas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        btnCapas.setText("Capas");
        btnCapas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapasActionPerformed(evt);
            }
        });
        menuCarga.add(btnCapas);

        btnImagenes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        btnImagenes.setText("Imagenes");
        btnImagenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImagenesActionPerformed(evt);
            }
        });
        menuCarga.add(btnImagenes);

        btnAlbumes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        btnAlbumes.setText("Albumes");
        btnAlbumes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlbumesActionPerformed(evt);
            }
        });
        menuCarga.add(btnAlbumes);

        jMenuBar1.add(menuCarga);

        menuReportes.setText("Reportes");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setText("Top5");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuReportes.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem2.setText("Recorridos");
        menuReportes.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem3.setText("Profundidad");
        menuReportes.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem4.setText("Capas Hojas");
        menuReportes.add(jMenuItem4);

        jMenuBar1.add(menuReportes);

        menuVer.setText("Ver");

        btnVerArbolCapas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        btnVerArbolCapas.setText("Arbol de Capas");
        btnVerArbolCapas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerArbolCapasActionPerformed(evt);
            }
        });
        menuVer.add(btnVerArbolCapas);

        btnVerArbolImagenes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        btnVerArbolImagenes.setText("Arbol de Imagenes");
        btnVerArbolImagenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerArbolImagenesActionPerformed(evt);
            }
        });
        menuVer.add(btnVerArbolImagenes);

        btnVerListAlbumes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        btnVerListAlbumes.setText("Listado de Albumes");
        btnVerListAlbumes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerListAlbumesActionPerformed(evt);
            }
        });
        menuVer.add(btnVerListAlbumes);

        jMenuBar1.add(menuVer);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCapasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapasActionPerformed
        // TODO add your handling code here:
        String capas = leer();
        analizarCapas(capas);
    }//GEN-LAST:event_btnCapasActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnVerCapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerCapaActionPerformed
        // TODO add your handling code here:
        if(comboCapa.getSelectedItem() == null){
            JOptionPane.showMessageDialog(null, "No hay capas.","Cliente",JOptionPane.ERROR_MESSAGE);
        }else{            
            String nombre = Main.actual.getDpi()+"_Capa"+comboCapa.getSelectedItem();
            ImageIcon imgIcon = new ImageIcon(System.getProperty("user.dir") + "\\"+nombre+".png");
            java.awt.Image imgEscalada = imgIcon.getImage().getScaledInstance(Imagenlbl.getWidth(),Imagenlbl.getHeight(), java.awt.Image.SCALE_SMOOTH);
            Icon iconoEscalado = new ImageIcon(imgEscalada);
            Imagenlbl.setIcon(iconoEscalado);
        }
    }//GEN-LAST:event_btnVerCapaActionPerformed

    private void comboCapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCapaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboCapaActionPerformed

    private void btnVerArbolImagenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerArbolImagenesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerArbolImagenesActionPerformed

    private void btnVerArbolCapasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerArbolCapasActionPerformed
        // TODO add your handling code here:
        Main.actual.graficarACapas();
        try {
            Thread.sleep(2*1000);
         } catch (Exception e) {
            System.out.println(e);
         }
        String nombre = Main.actual.getDpi()+"_Capas";
        ImageIcon imgIcon = new ImageIcon(System.getProperty("user.dir") + "\\"+nombre+".png");
        java.awt.Image imgEscalada = imgIcon.getImage().getScaledInstance(Imagenlbl.getWidth(),Imagenlbl.getHeight(), java.awt.Image.SCALE_SMOOTH);
        Icon iconoEscalado = new ImageIcon(imgEscalada);
        Imagenlbl.setIcon(iconoEscalado);
    }//GEN-LAST:event_btnVerArbolCapasActionPerformed

    private void btnModificarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarDatosActionPerformed
        // TODO add your handling code here:
        ModCliente actual = new ModCliente();
        actual.llenarlo(Main.actual.getDpi(), Main.actual.getNombre(), Main.actual.getPass());
        actual.setVisible(true);
    }//GEN-LAST:event_btnModificarDatosActionPerformed

    private void btnImagenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImagenesActionPerformed
        // TODO add your handling code here:
        String images = leer();
        analizarImage(images);
    }//GEN-LAST:event_btnImagenesActionPerformed

    private void btnAlbumesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlbumesActionPerformed
        // TODO add your handling code here:
        String arlbumes = leer();
        analizarAlbumes(arlbumes);
    }//GEN-LAST:event_btnAlbumesActionPerformed

    private void btnElimiarImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElimiarImgActionPerformed
        // TODO add your handling code here:
        if(comboImagen.getSelectedItem() == null){
            JOptionPane.showMessageDialog(null, "No Hay Imagenes","CLIENTE",JOptionPane.ERROR_MESSAGE);
        }else{
            String a = (String)comboImagen.getSelectedItem();
            int no = Integer.parseInt(a);
            
            Main.actual.eliminarImagen(no);
            JOptionPane.showMessageDialog(null, "Imagen Eliminada","CLIENTE",JOptionPane.INFORMATION_MESSAGE);
            
           int c = comboImagen.getSelectedIndex();
           comboImagen.removeItemAt(c);
        }
    }//GEN-LAST:event_btnElimiarImgActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        Inicio ini = new Inicio();
        ini.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void comboImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboImagenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboImagenActionPerformed

    private void btnVerListAlbumesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerListAlbumesActionPerformed
        // TODO add your handling code here:
        Main.actual.graficarAlbum();
        try {
            Thread.sleep(2*1000);
         } catch (Exception e) {
            System.out.println(e);
         }
        
        String nombre = Main.actual.getDpi()+"_Albumes";
        ImageIcon imgIcon = new ImageIcon(System.getProperty("user.dir") + "\\"+nombre+".png");
        java.awt.Image imgEscalada = imgIcon.getImage().getScaledInstance(Imagenlbl.getWidth(),Imagenlbl.getHeight(), java.awt.Image.SCALE_SMOOTH);
        Icon iconoEscalado = new ImageIcon(imgEscalada);
        Imagenlbl.setIcon(iconoEscalado);
    }//GEN-LAST:event_btnVerListAlbumesActionPerformed

    private void btnVerImgAcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerImgAcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerImgAcActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Imagenlbl;
    private javax.swing.JMenuItem btnAlbumes;
    private javax.swing.JMenuItem btnCapas;
    private javax.swing.JButton btnElimiarImg;
    private javax.swing.JMenuItem btnImagenes;
    private javax.swing.JButton btnModificarDatos;
    private javax.swing.JButton btnSalir;
    private javax.swing.JMenuItem btnVerArbolCapas;
    private javax.swing.JMenuItem btnVerArbolImagenes;
    private javax.swing.JButton btnVerCapa;
    private javax.swing.JButton btnVerImgAc;
    private javax.swing.JMenuItem btnVerListAlbumes;
    public javax.swing.JComboBox<String> comboCapa;
    public javax.swing.JComboBox<String> comboImagen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenu menuCarga;
    private javax.swing.JMenu menuReportes;
    private javax.swing.JMenu menuVer;
    private javax.swing.JButton verArboldeCapas;
    // End of variables declaration//GEN-END:variables

    
    public static String leer(){
        int n = 0;
        Scanner entrada = null;
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.showOpenDialog(fileChooser);
        String t = "";
        try {
            String ruta = fileChooser.getSelectedFile().getAbsolutePath();                                        
            File f = new File(ruta);
            entrada = new Scanner(f);
            while (entrada.hasNext()) {
                if(n==0){
                    t += entrada.nextLine();
                }else{
                    t += "\n" + entrada.nextLine();
                }
                n+=1;
            }
            return t;
        } catch (FileNotFoundException e) {
            System.out.println(e.getMessage());
        } catch (NullPointerException e) {
            System.out.println("No se ha seleccionado ningún fichero");
        } catch (Exception e) {
            System.out.println(e.getMessage());
        } finally {
            if (entrada != null) {
                entrada.close();
            }
        }
        return "";
    }
    
    public void analizarCapas(String text){
        JsonParser parser = new JsonParser();
        JsonArray gsonArr = parser.parse(text).getAsJsonArray();
        for (JsonElement obj : gsonArr) {
            JsonObject gsonObj = obj.getAsJsonObject();
            int id = gsonObj.get("id_capa").getAsInt();
            JsonArray pixeles = gsonObj.get("pixeles").getAsJsonArray();
            MatrizDispersa mcapa = new MatrizDispersa();
            for(JsonElement pix: pixeles){
                JsonObject ps = pix.getAsJsonObject();
                int y  = ps.get("fila").getAsInt();
                int x  = ps.get("columna").getAsInt();
                String color = ps.get("color").getAsString();
                mcapa.insertar(color, x, y);
            }
            Capa nueva = new Capa(id,mcapa);   
            String nombre = Main.actual.getDpi()+"_Capa"+id;
            mcapa.graficarMatriz(nombre);
            Main.graficarDot(nombre);
            Main.actual.agregarCapa(nueva);
            comboCapa.addItem(""+id);
        }
        JOptionPane.showMessageDialog(null, "Capas creadas exitosamente.","Cliente",JOptionPane.INFORMATION_MESSAGE);
    }
    
    public void analizarImage(String text){
        JsonParser parser = new JsonParser();
        JsonArray gsonArr = parser.parse(text).getAsJsonArray();
        for (JsonElement obj : gsonArr) {
            JsonObject gsonObj = obj.getAsJsonObject();
            int id = gsonObj.get("id").getAsInt();
            ABB im = new ABB();
            JsonArray capas = gsonObj.get("capas").getAsJsonArray();
            for(JsonElement pix: capas){
                int c = pix.getAsInt();
                im.insertar(new Capa(c,null));
            }
            Image nImagen = new Image(id,im);
            Main.actual.agregarImagen(nImagen);
            String dpi = Main.actual.getDpi()+"_";
            
            //PreOrden
            MatrizDispersa pre = im.crearImagen("Pre");
            pre.graficarMatriz(dpi+"pre_img"+id);
            Main.graficarDot(dpi+"pre_img"+id);
            
            //InOrden
            MatrizDispersa in = im.crearImagen("In");
            in.graficarMatriz(dpi+"in_img"+id);
            Main.graficarDot(dpi+"in_img"+id);
            
            //PostOrden
            MatrizDispersa post = im.crearImagen("Post");
            post.graficarMatriz(dpi+"post_img"+id);
            Main.graficarDot(dpi+"post_img"+id);
      
            comboImagen.addItem(""+id);
        }
        
        JOptionPane.showMessageDialog(null, "Imagenes Creadas","CLIENTE",JOptionPane.INFORMATION_MESSAGE);
    }
    
    public static void analizarAlbumes(String text){
        JsonParser parser = new JsonParser();
        JsonArray gsonArr = parser.parse(text).getAsJsonArray();
        for (JsonElement obj : gsonArr) {
            JsonObject gsonObj = obj.getAsJsonObject();
            String nombre = gsonObj.get("nombre_album").getAsString();
            JsonArray imgs = gsonObj.get("imgs").getAsJsonArray();
            List miLista = new List();
            for(JsonElement pix: imgs){
                int c = pix.getAsInt();
                miLista.insertar(c);
            }
            Album mmalbum = new Album(nombre,miLista);
            Main.actual.agregarAlbum(mmalbum);
        }
        JOptionPane.showMessageDialog(null, "Albumes Creados.","CLIENTE",JOptionPane.INFORMATION_MESSAGE);
    }

}
